using System;
using Microsoft.AspNetCore.Identity;

namespace Coffee.Core.User.Infrastructure
{
    public class ApplicationUser : IdentityUser
    {

        // public int Id { get; set; }
        // public string UserName { get; set; }
        // public string PhoneNumber { get; set; }
        public string UserId { get; set; }          // According to Auth (Generated By Auth Server)
        public string LoginId { get; set; }         // According to Auth (Should be Country Code + phone number)
        public string CountryCode { get; set; }
        public string WechatId { get; set; }
        public string VoucherCode { get; set; }
        public int RegionId { get; set; }
        public int KYCLevel { get; set; }
        public DateTime KYCUpdatedDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public string AvatarImageUrl { get; set; }
        public string AvatarImageFileName { get; set; }
        public string ReferralCode { get; set; }
        public string ProfileName { get; set; }
        public string PublicKey { get; set; }
        // public UserPreference UserPreference  { get; set; }
        public UserKYC2 UserKCY2 { get; set; }
    }
}
